<?php

declare(strict_types=1);

/**
 * ISER - Asset Manager
 *
 * Generates dynamic CSS files with theme customizations
 * Handles CSS variable injection, minification, and cache busting
 *
 * @package ISER\Theme
 * @author ISER Development Team
 * @copyright 2024 ISER
 * @license Proprietary
 */

namespace ISER\Theme;

use ISER\Core\Database\Database;

/**
 * AssetManager Class
 *
 * Generates and manages dynamic theme CSS files
 */
class AssetManager
{
    /**
     * Database instance
     */
    private Database $db;

    /**
     * Theme configurator instance
     */
    private ThemeConfigurator $configurator;

    /**
     * Public path for generated files
     */
    private string $publicPath;

    /**
     * CSS output directory
     */
    private string $cssDir;

    /**
     * Constructor
     *
     * @param Database $db Database instance
     * @param ThemeConfigurator $configurator Theme configurator
     * @param string|null $publicPath Optional public path override
     */
    public function __construct(
        Database $db,
        ThemeConfigurator $configurator,
        ?string $publicPath = null
    ) {
        $this->db = $db;
        $this->configurator = $configurator;
        $this->publicPath = $publicPath ?? $_SERVER['DOCUMENT_ROOT'] ?? __DIR__ . '/../../public';
        $this->cssDir = $this->publicPath . '/theme';

        // Ensure CSS directory exists
        if (!is_dir($this->cssDir)) {
            @mkdir($this->cssDir, 0755, true);
        }
    }

    /**
     * Generate custom CSS file with theme variables
     *
     * @return string Generated CSS file path (relative to public)
     */
    public function generateCustomCSS(): string
    {
        // Get all theme configurations
        $config = $this->configurator->getAll();

        // Generate CSS content
        $css = $this->generateCSSVariables($config);
        $css .= "\n\n" . $this->generateDarkModeCSS($config);
        $css .= "\n\n" . $this->generateUtilityClasses($config);

        // Minify CSS
        $css = $this->minifyCSS($css);

        // Generate filename with hash
        $hash = $this->generateCSSHash($css);
        $filename = "custom-colors-{$hash}.css";
        $filepath = $this->cssDir . '/' . $filename;

        // Write CSS file
        if (file_put_contents($filepath, $css) === false) {
            error_log("Failed to write CSS file: $filepath");
            return '';
        }

        // Clean up old CSS files
        $this->cleanupOldFiles();

        // Return relative path
        return "/theme/{$filename}";
    }

    /**
     * Generate CSS variables from configuration
     *
     * @param array $config Theme configuration
     * @return string CSS content
     */
    private function generateCSSVariables(array $config): string
    {
        $css = "/* Generated Theme CSS - " . date('Y-m-d H:i:s') . " */\n";
        $css .= "/* DO NOT EDIT - Auto-generated by ThemeConfigurator */\n\n";
        $css .= ":root {\n";

        // Color variables
        $colors = $this->configurator->getGroup('colors');
        foreach ($colors as $name => $value) {
            $css .= "  --color-{$name}: {$value};\n";

            // Generate RGB values for transparency support
            if (ColorManager::isValidHex($value)) {
                [$r, $g, $b] = ColorManager::hexToRgb($value);
                $css .= "  --color-{$name}-rgb: {$r}, {$g}, {$b};\n";

                // Generate variants
                $variants = ColorManager::generateVariants($value);
                $css .= "  --color-{$name}-light: {$variants['light']};\n";
                $css .= "  --color-{$name}-dark: {$variants['dark']};\n";
                $css .= "  --color-{$name}-contrast: {$variants['contrast']};\n";
            }
        }

        // Typography variables
        $typography = $this->configurator->getGroup('typography');
        if (isset($typography['font_heading'])) {
            $css .= "\n  /* Typography */\n";
            $css .= "  --font-heading: {$typography['font_heading']};\n";
        }
        if (isset($typography['font_body'])) {
            $css .= "  --font-body: {$typography['font_body']};\n";
        }
        if (isset($typography['font_mono'])) {
            $css .= "  --font-mono: {$typography['font_mono']};\n";
        }
        if (isset($typography['base_font_size'])) {
            $css .= "  --font-size-base: {$typography['base_font_size']};\n";
        }
        if (isset($typography['line_height'])) {
            $css .= "  --line-height-base: {$typography['line_height']};\n";
        }

        // Layout variables
        $layout = $this->configurator->getGroup('layout');
        if (!empty($layout)) {
            $css .= "\n  /* Layout */\n";
            if (isset($layout['sidebar_width'])) {
                $css .= "  --sidebar-width: {$layout['sidebar_width']};\n";
            }
            if (isset($layout['navbar_height'])) {
                $css .= "  --navbar-height: {$layout['navbar_height']};\n";
            }
            if (isset($layout['container_width'])) {
                $css .= "  --container-max-width: {$layout['container_width']};\n";
            }
        }

        $css .= "}\n";

        return $css;
    }

    /**
     * Generate dark mode CSS
     *
     * @param array $config Theme configuration
     * @return string CSS content
     */
    private function generateDarkModeCSS(array $config): string
    {
        $css = "/* Dark Mode */\n";
        $css .= "[data-theme=\"dark\"] {\n";

        // Get colors and adjust for dark mode
        $colors = $this->configurator->getGroup('colors');

        foreach ($colors as $name => $value) {
            if (!ColorManager::isValidHex($value)) {
                continue;
            }

            // Adjust colors for dark mode
            $darkValue = $value;

            // Lighten dark colors, darken light colors
            if (in_array($name, ['primary', 'secondary', 'success', 'danger', 'warning', 'info'])) {
                // Lighten accent colors for better visibility on dark background
                $darkValue = ColorManager::lighten($value, 15);
            } elseif ($name === 'light') {
                // Invert light to dark
                $darkValue = '#1a2332';
            } elseif ($name === 'dark') {
                // Use lighter version of dark
                $darkValue = '#2d3748';
            }

            $css .= "  --color-{$name}: {$darkValue};\n";

            // Regenerate RGB and variants
            [$r, $g, $b] = ColorManager::hexToRgb($darkValue);
            $css .= "  --color-{$name}-rgb: {$r}, {$g}, {$b};\n";
        }

        // Dark mode specific variables
        $css .= "\n  /* Dark mode backgrounds and text */\n";
        $css .= "  --bg-primary: #0b1727;\n";
        $css .= "  --bg-secondary: #1a2332;\n";
        $css .= "  --bg-tertiary: #2d3748;\n";
        $css .= "  --text-primary: #e9ecef;\n";
        $css .= "  --text-secondary: #adb5bd;\n";
        $css .= "  --text-tertiary: #6c757d;\n";
        $css .= "  --border-color: #2d3748;\n";

        $css .= "}\n";

        return $css;
    }

    /**
     * Generate utility classes using theme variables
     *
     * @param array $config Theme configuration
     * @return string CSS content
     */
    private function generateUtilityClasses(array $config): string
    {
        $css = "/* Utility Classes */\n\n";

        // Typography utilities
        $css .= "body {\n";
        $css .= "  font-family: var(--font-body, 'Open Sans', sans-serif);\n";
        $css .= "  font-size: var(--font-size-base, 16px);\n";
        $css .= "  line-height: var(--line-height-base, 1.6);\n";
        $css .= "  color: var(--text-primary, #212529);\n";
        $css .= "  background-color: var(--bg-primary, #ffffff);\n";
        $css .= "}\n\n";

        $css .= "h1, h2, h3, h4, h5, h6 {\n";
        $css .= "  font-family: var(--font-heading, 'Montserrat', sans-serif);\n";
        $css .= "}\n\n";

        $css .= "code, pre, kbd, samp {\n";
        $css .= "  font-family: var(--font-mono, 'Courier New', monospace);\n";
        $css .= "}\n\n";

        // Button utilities
        $colors = ['primary', 'secondary', 'success', 'danger', 'warning', 'info'];
        foreach ($colors as $color) {
            $css .= ".btn-{$color} {\n";
            $css .= "  background-color: var(--color-{$color});\n";
            $css .= "  border-color: var(--color-{$color});\n";
            $css .= "  color: var(--color-{$color}-contrast);\n";
            $css .= "}\n\n";

            $css .= ".btn-{$color}:hover {\n";
            $css .= "  background-color: var(--color-{$color}-dark);\n";
            $css .= "  border-color: var(--color-{$color}-dark);\n";
            $css .= "}\n\n";

            $css .= ".btn-outline-{$color} {\n";
            $css .= "  color: var(--color-{$color});\n";
            $css .= "  border-color: var(--color-{$color});\n";
            $css .= "}\n\n";

            $css .= ".btn-outline-{$color}:hover {\n";
            $css .= "  background-color: var(--color-{$color});\n";
            $css .= "  color: var(--color-{$color}-contrast);\n";
            $css .= "}\n\n";
        }

        // Badge utilities
        foreach ($colors as $color) {
            $css .= ".badge-{$color} {\n";
            $css .= "  background-color: var(--color-{$color});\n";
            $css .= "  color: var(--color-{$color}-contrast);\n";
            $css .= "}\n\n";
        }

        // Alert utilities
        foreach ($colors as $color) {
            $css .= ".alert-{$color} {\n";
            $css .= "  background-color: rgba(var(--color-{$color}-rgb), 0.1);\n";
            $css .= "  border-color: var(--color-{$color});\n";
            $css .= "  color: var(--color-{$color}-dark);\n";
            $css .= "}\n\n";
        }

        // Background utilities
        foreach ($colors as $color) {
            $css .= ".bg-{$color} {\n";
            $css .= "  background-color: var(--color-{$color}) !important;\n";
            $css .= "  color: var(--color-{$color}-contrast) !important;\n";
            $css .= "}\n\n";
        }

        // Text color utilities
        foreach ($colors as $color) {
            $css .= ".text-{$color} {\n";
            $css .= "  color: var(--color-{$color}) !important;\n";
            $css .= "}\n\n";
        }

        return $css;
    }

    /**
     * Minify CSS content
     *
     * @param string $css CSS content
     * @return string Minified CSS
     */
    private function minifyCSS(string $css): string
    {
        // Remove comments
        $css = preg_replace('!/\*[^*]*\*+([^/][^*]*\*+)*/!', '', $css);

        // Remove whitespace
        $css = str_replace(["\r\n", "\r", "\n", "\t"], '', $css);

        // Remove spaces around special characters
        $css = preg_replace('/\s*([{}:;,])\s*/', '$1', $css);

        // Remove last semicolon in block
        $css = str_replace(';}', '}', $css);

        // Remove unnecessary spaces
        $css = preg_replace('/\s+/', ' ', $css);

        return trim($css);
    }

    /**
     * Generate CSS file hash for cache busting
     *
     * @param string $content CSS content
     * @return string Hash string (8 characters)
     */
    private function generateCSSHash(string $content): string
    {
        return substr(hash('sha256', $content), 0, 8);
    }

    /**
     * Delete old CSS files (keep only latest 3)
     *
     * @return int Number of files deleted
     */
    public function cleanupOldFiles(): int
    {
        $deleted = 0;

        // Get all custom CSS files
        $files = glob($this->cssDir . '/custom-colors-*.css');

        if (empty($files) || count($files) <= 3) {
            return 0;
        }

        // Sort by modification time (newest first)
        usort($files, function($a, $b) {
            return filemtime($b) - filemtime($a);
        });

        // Keep only latest 3, delete the rest
        $filesToDelete = array_slice($files, 3);

        foreach ($filesToDelete as $file) {
            if (unlink($file)) {
                $deleted++;
            }
        }

        return $deleted;
    }

    /**
     * Get current CSS file URL
     *
     * @return string CSS file URL or empty if not generated
     */
    public function getCurrentCSSUrl(): string
    {
        $files = glob($this->cssDir . '/custom-colors-*.css');

        if (empty($files)) {
            return '';
        }

        // Sort by modification time (newest first)
        usort($files, function($a, $b) {
            return filemtime($b) - filemtime($a);
        });

        $filename = basename($files[0]);

        return "/theme/{$filename}";
    }

    /**
     * Force regenerate CSS (invalidate cache)
     *
     * @return string New CSS file path
     */
    public function regenerate(): string
    {
        return $this->generateCustomCSS();
    }

    /**
     * Check if CSS file exists and is current
     *
     * @return bool True if current CSS exists
     */
    public function isGenerated(): bool
    {
        $files = glob($this->cssDir . '/custom-colors-*.css');
        return !empty($files);
    }

    /**
     * Get CSS file modification time
     *
     * @return int Unix timestamp or 0 if not found
     */
    public function getModificationTime(): int
    {
        $files = glob($this->cssDir . '/custom-colors-*.css');

        if (empty($files)) {
            return 0;
        }

        usort($files, function($a, $b) {
            return filemtime($b) - filemtime($a);
        });

        return filemtime($files[0]);
    }
}
